---
packages:
  - acl
  - autoconf
  - automake
  - bison
  - build-essential
  - clamav
  - clamav-daemon
  - curl
  - git
  - git-core
  - imagemagick
  - libc6-dev
  - libcurl4-openssl-dev
  - libmagickwand-dev
  - libreadline6
  - libreadline6-dev
  - libreoffice
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libxml2-dev
  - libxslt-dev
  - libxvidcore-dev
  - libyaml-dev
  - ncurses-dev
  - openssl
  - pkg-config
  - redis-server
  - subversion
  - vim
  - xfsprogs
  - zlib1g
  - zlib1g-dev
