---
hydra_db: my_hydra_db
hydra_pg_user: my_hydra_pg_user
hydra_pg_pass: my_hydra_pg_pass
# needed for capistrano configuration
shared_root: /opt/sufia-project/shared
capistrano_user: deploy
capistrano_group: deploy
