---
install_path: /opt/install
install_user: install
install_group: install
become_user: install
app_root: /opt/sufia-project/current
rails_env: production
pg_pass: postgres
hydra_db: my_hydra_db
hydra_pg_user: my_hydra_pg_user
hydra_pg_pass: my_hydra_pg_pass
# needed for resque-pool init script
capistrano_user: deploy
