---
# host group must be specified at command line, e.g.
# ansible-playbook configure.yml -e hosts=ec2hosts
# TODO: it should work to default to all ec2hosts in this way:
#   hosts: ec2hosts,&{{ hosts | default("all") }}
#   But I couldn't get this to work for me.
- name: configuration
  hosts: "{{ hosts }}"
  user: ubuntu
  gather_facts: true
  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup }
    - { role: ruby }
    - { role: hydra-stack/install }
    - { role: hydra-stack/config-capistrano }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }
    # if using RIIIF, uncomment this role
    # - { role: RIIIF }
    - { role: apache-passenger/install }
    - { role: apache-passenger/config }
    - { role: app-config }
