- name: provision a vagrant box to mimic a production environment as closely as possible.
  hosts: vagrant
  remote_user: vagrant
  roles:
    - { role: packages, sudo: yes }
    - { role: housekeeping, sudo: yes }
    - { role: ruby }
    - { role: hydra-stack }
    - { role: services }
    - { role: passenger, sudo: yes }
    - { role: app-config, sudo: yes }
