- name: provision an ec2 instance
  ec2:
    key_name: "{{ ec2_key }}" 
    region: "{{ ec2_region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    count: 1
    state: present
    count_tag:
      Name: "{{ aws_tag }}"
    instance_tags: 
      Name: "{{ aws_tag }}"
  register: ec2

- name: attach volume to new instance
  ec2_vol:
    instance: "{{ ec2.instance_ids }}"
    region: "{{ ec2_region }}"
    device_name: /dev/sdf
    volume_size: 40
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
  register: ec2_vol

  # first stab at dynamic inventory management on ec2
  # finishing this is out of scope for current project
  # add_host only adds to in-memory list of hosts
- name: Add all instance public IPs to in-memory host group
  add_host: hostname={{ item.public_ip }} groups=newboxes
  with_items: ec2.instances

- name: Add all instance public IPs to on-disc host group
  lineinfile: dest=hosts line={{ item.public_ip }} insertafter=ec2hosts
  with_items: ec2.instances

- name: give ssh time to come up
  pause: minutes=2
