---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/main.yml
#
# Launches a new ec2 instance and attaches dedicated data volume

- name: Set up internal network security group
  include: internal_group.yml

- name: Build EC2 machines
  include: machine.yml

