---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/main.yml
#
# installs solr and fedora in production mode as servlets under tomcat
#
- include: tomcat.yml
- include: solr_5.yml
  when: solr_version | match("^[5-9]\.\d{1,2}\.\d{1,2}")
- include: solr_4.yml
  when: solr_version | match("^4\.\d{1-2}\.\d{1-2}")
- include: fedora.yml
