---
- name: install ffmpeg libraries
  become: yes
  package: name={{ item }} state=present
  with_items:
      - autoconf
      - automake
      - cmake
      # - freetype-devel
      - gcc
      # - gcc-c++
      - git
      - libtool
      - make
      - mercurial
      - nasm
      # - pkgconfig
      # - zlib-devel

- name: remove package ffmpeg
  become: yes
  package: name=ffmpeg state=absent

- name: create sources dir
  become: yes
  file: owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} state=directory path={{ ffmpeg_path }}

- name: ff add ldconfig for ffmpeg lib dir
  become: yes
  copy: dest=/etc/ld.so.conf.d/ffmpeg.conf content={{ ffmpeg_prefix }}/lib owner=root group=root mode=0644 

- name: ff export ffmpeg bin dir to PATH
  become: yes
  template: src=profile.j2 dest=/etc/profile.d/ffmpeg.sh