---
- name: clone fdk-aac source
  git: repo=https://github.com/mstorsjo/fdk-aac.git depth=1 accept_hostkey=yes dest={{ ffmpeg_path }}/fdk-aac force=yes

- name: clean the fdk-aac repo
  shell: cd {{ ffmpeg_path }}/fdk-aac && autoreconf -fiv

- name: configure fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && ./configure --disable-shared creates={{ ffmpeg_path }}/fdk-aac/Makefile

- name: make fdk-aac
  shell: cd {{ ffmpeg_path }}/fdk-aac && make 

- name: install fdk-aac
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make install

- name: clean the fkd-aac repo
  become: yes
  shell: cd {{ ffmpeg_path }}/fdk-aac && make distclean