---
# ROLE: hydra-tutorials
# roles/hydra-tutorials/tasks/main.yml
#
# setup for Dive-Into-Hydra and other workshop and online tutorials
#

- name: Download solr and fedora runtime files
  include: wrappers.yml
    
- name: Setup Hyrax sample application
  include: hyrax-sample.yml
