---
project_name: sufia-project
app_root: /opt/sufia-project/current
server_name: 127.0.0.1
ssl_crt_location: /etc/ssl/server.crt
ssl_key_location: /etc/ssl/private/server.key
# this should be blank / undefined for self-signed certs.
# provided here just as an example; specify it in a local file if needed.
#ssl_intermediate_directive: SSLCertificateChainFile /etc/ssl/certs/my-intermediate-cert
